config/routes.rb
require 'sidekiq/web'

Liveinspired::Application.routes.draw do

  resources :chatrooms
  mount Sidekiq::Web => '/sidekiq'

  root :to => "home#index"
  devise_for :users
  namespace :admin do
    resources :home, only: %i(index)
    resources :channels, only: %i(index)
  end
  get 'admin', to: 'admin/home#index'
  resources :keywords, only: [:index]
  resources :chatrooms do
    resources :chatters, only: [:index] do
      collection do
        post :add_to_chatroom
        post :remove_from_chatroom
      end
    end
    resources :chats
  end
  resources :channels do
    member do
      get  'list_subscribers'
      get  'messages_report'
      post 'delete_all_messages'
      get  'timeline'
      get  'export'
      get  'all'
    end
    resources :messages do
      member do
        post 'broadcast'
        post 'move_up'
        post 'move_down'
        get  'responses'
      end
      collection do
        get 'select_import'
        post 'import'
        post 'update_seq_no'
      end
      resources :response_actions do
        collection do
          get 'select_import'
          post 'import'
        end
      end
    end
  end
  post 'channels/:channel_id/add_subscriber/:id',    to: 'channels#add_subscriber',    :as => 'channel_add_subscriber'
  post 'channels/:channel_id/remove_subscriber/:id', to: 'channels#remove_subscriber', :as => 'channel_remove_subscriber'

  resources :channel_groups, :except => [:index] do
    member do
      get 'messages_report'
    end
  end
  post 'channel_groups/:channel_group_id/remove_channel/:id', to: 'channel_groups#remove_channel',  :as => 'channel_group_remove_channel'

  resources :rules
  resources :users do
    member do
      get :activity
    end
  end
  resources :subscribers do
    resources :subscriber_responses, only: %i(index)
    member do
      get :download_activity
    end
  end
  resources :subscriber_activities, :except=>[:new,:create,:destroy] do
    member do
      post 'reprocess'
    end
  end

  resources :downloads,           only: [:index]
  resources :service_identifiers, only: [:index]

  match 'subscribe/:channel_group_id' => "home#new_web_subscriber", :via => [:get, :post]
  match 'thank_you' => "home#sign_up_success", via: [:get]
  match 'twilio' =>'twilio#callback', :via => [:post]

  match 'help/user_show',            via: [:get]
  match 'help/edit_channel',         via: [:get]
  match 'help/edit_message',         via: [:get]
  match 'help/index_channels',       via: [:get]
  match 'help/edit_response_action', via: [:get]
  match 'help/glossary',             via: [:get]

end

app/views/shared/_absolute_schedule.html.slim
.form-group
  label.col-sm-5.string.control-label Scheduling Preference
  .col-sm-7
    .radio
      label
        = radio_button_tag :one_time_or_recurring, "one_time", message.recurring_schedule.blank?
        | One time
    .radio
      label
        = radio_button_tag :one_time_or_recurring, "recurring", message.recurring_schedule.present?
        | Recurring

= f.input :next_send_time, as: :datetime_picker

#recurring_schedule.form-group
  label.string.control-label.col-sm-5 for="message_schedule" Schedule
  .col-sm-7
    = f.select_recurring :recurring_schedule, message.recurring_schedule, {:allow_blank => true }, class: "form-control"

#rs-target data-initial-value="#{message.recurring_schedule}"

- content_for :head_js
  javascript:

    $(document).ready(function () {
      var initializing_rule = $('#rs-target').data('initial-value');
      console.log('initializing rule is ' + initializing_rule);

      switch ($('input[name=one_time_or_recurring]:checked').val()) {
        case 'one_time':
          $('.message_next_send_time').show();
          $('#recurring_schedule').hide();
          $('#rs-target').hide();
          break;
        case 'recurring':
          $('.message_next_send_time').hide();
          $('#rs-target').show();

          $('#recurring_schedule').show();
          break;
      }

      $('input[name=one_time_or_recurring]').on('click', function() {
        var one_time_or_recurring = $(this).val();
        switch (one_time_or_recurring) {
          case 'one_time':
            $('.message_next_send_time').show();
            $('#rs-target').hide();
            $('#recurring_schedule').hide();
            break;
          case 'recurring':
            $('#rs-target').show();
            $('.message_next_send_time').hide();
            $('#recurring_schedule').show();
            break;
        }
      });

      $('#rs_frequency:visible').livequery(function() {
        var rs_frequency = $(this).val();
        switch (rs_frequency) {
          case 'Daily':
            $('.daily_options').css('display', 'inline');
            $('.weekly_options').css('display', 'none');
            $('.monthly_options').css('display', 'none');
            $('.yearly_options').css('display', 'none');
            break;
          case 'Weekly':
            $('.daily_options').css('display', 'none');
            $('.weekly_options').css('display', 'inline');
            $('.monthly_options').css('display', 'none');
            $('.yearly_options').css('display', 'none');
            break;
          case 'Monthly':
            $('.daily_options').css('display', 'none');
            $('.weekly_options').css('display', 'none');
            $('.monthly_options').css('display', 'inline');
            $('.yearly_options').css('display', 'none');
            break;
          case 'Yearly':
            $('.daily_options').css('display', 'none');
            $('.weekly_options').css('display', 'none');
            $('.monthly_options').css('display', 'none');
            $('.yearly_options').css('display', 'inline');
            break;
        }
      });
    });

app/views/shared/_channel_group_list.html.slim
#channel-groups-section.panel.panel-default.shared-table
  .panel-heading
    .row
      .col-md-4
        = raw "#{icon('folder-open')} Channel Groups"
        span.badge.margin-left-10 #{@channel_groups.count}
      .col-md-5
        =form_tag request.url, method: :get do
          .input-group
            = search_field_tag :channel_group_search, params[:channel_group_search], placeholder: 'Search by name', class: 'form-control'
            .input-group-btn
              = button_tag('Search', class: 'btn btn-default')
      .col-md-3.text-right.pull-right
        = link_to new_channel_group_path, class: "btn btn-primary btn-xs", id: 'channel-group-new'
          span.glyphicon.glyphicon-plus
          | New Group

  .panel-body
    - if @channel_groups && @channel_groups.count > 0
      table.table.table-striped#channel_groups_table
        thead
          th Name
          th.text-center Channels
          th
        tbody
          - @channel_groups.each do |channel_group|
            tr id="channel_group_#{channel_group.id}"
              td
                .name
                  = link_to channel_group_path(channel_group)
                    = "#{channel_group.name}"
                .tparty style="font-size: 70%; color: #ccc;"
                  | #{channel_group.tparty_keyword}
              td.text-center
                = channel_group.channels.count
              td.text-right.pull-right
                = link_to "Edit", edit_channel_group_path(channel_group), class: "btn btn-default btn-xs"
      .row
        .col-md-12.text-center
          = will_paginate @channel_groups, param_name: "channel_groups_page"

    - else
      .notification-well.text-center
        .icon
          span.glyphicon.glyphicon-folder-open
        .message
          h4 No Channel Groups
          p No channels groups configured
          .new
            = link_to "Create new channel group", new_channel_group_path, class: "btn btn-primary"

app/views/shared/_channel_list.html.slim
- channel_model_class = Channel
// If there is no channel group, define it as nil
- channel_group = defined?(channel_group) ? channel_group : nil

#channels-section.panel.panel-default.shared-table
  .panel-heading
    .row
      .col-md-4
        span.icon
        - if channel_group
          = raw "#{icon('list-ol')} #{channel_group.name} channels"
          span.badge.margin-left-10 #{@channels.count}
        - else
          = raw "#{icon('list-ol')} Channels"
          span.badge.margin-left-10 #{@channels.count}
      .col-md-5
        =form_tag request.url, method: :get do
          .input-group
            = search_field_tag :channel_search, params[:channel_search], placeholder: 'Search for channel',class: 'form-control'
            .input-group-btn
              = button_tag('Search', class: 'btn btn-default')
      .col-md-3.pull-right.text-right
        - if channel_group
          = link_to new_channel_path(channel_group_id: channel_group.id), class: "btn btn-primary btn-xs", id: 'channel-new' do
            span.glyphicon.glyphicon-plus
            | New Channel
        - else
          = link_to new_channel_path, class: "btn btn-primary btn-xs", id: 'channel-new' do
            span.glyphicon.glyphicon-plus
            | New Channel

  .panel-body
    - if @channels && @channels.count > 0
      table.table.table-striped#channels_table
        thead
          tr
            th = channel_model_class.human_attribute_name(:name)
            th.text-center Keyword
            th.text-center title="How many subscribers does this channel have?"
              =icon('user')
            th.text-center title="How many messages does this channel have?"
              =icon('envelope')
            th
        tbody
          - @channels.each do |channel|
            tr id="channel_#{channel.id}" class="channel-row-#{channel.active == true ? 'active' : 'not-active'}"
              td
                .name
                  = link_to channel.name, channel_path(channel)
                .details style="font-size: 70%; color: #ccc;"
                  | #{channel.id}: #{ channel.type.to_s.gsub('MessagesChannel', '').titleize }
                .tparty style="font-size: 70%; color: #ccc;"
                  | #{channel.tparty_keyword}
              td.text-center = channel.keyword
              td.text-center = channel.subscribers.count
              td.text-center = channel.messages.count
              td.text-right.pull-right
                = link_to t(".edit", default: t("helpers.links.edit")),
                          edit_channel_path(channel),
                          class: "btn btn-default btn-xs"
      .row
        .col-md-12.text-center
          = will_paginate @channels, param_name: "channels_page"

    - else
      .notification-well.text-center
        .icon
          span.glyphicon.glyphicon-list
        .message
          h4 No Channels
          p No channels configured
          .new
            - if channel_group
              = link_to new_channel_path(channel_group_id: channel_group.id), class: 'btn btn-primary btn-xs' do
                span.glyphicon.glyphicon-plus
            - else
              = link_to new_channel_path, class: 'btn btn-primary btn-xs' do
                span.glyphicon.glyphicon-plus

app/views/shared/_chatrooms_list.html.slim
- message_model_class = Message

#chatrooms-section.panel.panel-default.shared-table
  .panel-heading
    .row
      .col-md-4
        .panel-title Chatrooms
        .counts
      .col-md-3.pull-right.text-right
        = link_to new_chatroom_path, class: "btn btn-primary btn-xs", id: 'message-new' do
          span.glyphicon.glyphicon-plus
          | New Chatroom

  .panel-body
    - if @chatrooms && @chatrooms.size > 0
      .row
        .col-md-12
          table.table.table-striped#chatrooms_table
            thead
              tr
                th Room
                th Created at
                th Subscribers Count
                th
            tbody
              - @chatrooms.each_with_index do |chatroom, index|
                tr.chatroom-row id="chatroom_#{chatroom.id}"
                  td = link_to(chatroom.name, chatroom_path(chatroom))
                  td = chatroom.created_at
                  td = chatroom.subscribers.count
                  td.text-right.col-md-3
                    => link_to 'Edit', edit_chatroom_path(chatroom), class: 'btn btn-default btn-xs'
      .row
        .col-md-12.text-center
          = will_paginate @chatrooms, param_name: "chatrooms_page"
    - else
      .notification-well
        .icon
          i.fa.fa-commenting
        .message
          h4 No Chatrooms
          p Chat rooms are created to let users chat with each other for encouragement and support.
          .add
            = link_to new_chatroom_path, class: "btn btn-primary"
              span.glyphicon.glyphicon-plus
              | Add new chatroom

app/views/shared/_helpful_links.html.slim
.panel.panel-default
  .panel-heading
    | Helpful Links
  .panel-body
    .row
      .col-md-12
        ul#helpful_links
          li= link_to "See your assigned service identifiers for channel setup", service_identifiers_path, target: "_blank"
          li= link_to "Download a message template for importing bulk messages", downloads_path, target: "_blank"

app/views/shared/_message_list.html.slim
- message_model_class = Message

#messages-section.panel.panel-default.shared-table
  .panel-heading
    .row
      .col-md-4
        .panel-title Messages
        .counts
          - @message_counts_by_type.each do |type, count|
            = link_to "#{type.gsub(/Message$/, '')}(#{count})", channel_path(@channel, message_type: type)
      .col-md-5
        =form_tag request.url, method: :get do
          .input-group
            = search_field_tag :message_search, params[:message_search], placeholder: 'Message text',class: 'form-control'
            .input-group-btn
              = button_tag('Search', class: 'btn btn-default')
      .col-md-3.pull-right.text-right
        = link_to new_channel_message_path(@channel), class: "btn btn-primary btn-xs", id: 'message-new' do
          span.glyphicon.glyphicon-plus
          | New Message

  .panel-body
    - if @messages && @messages.size > 0
      .row
        .col-md-12
          table.table.table-striped#messages_table
            thead
              tr
                th Text
                th
            tbody
              - @messages.each_with_index do |message, index|
                - message = message.decorate
                tr id="message_#{message.id}" class="message-row-#{message.active == true ? 'active' : 'not-active'}"
                   - if @channel.sequenced?
                     td.col-md-1
                       => link_to move_up_channel_message_path(@channel, message), method: :post, class: "btn btn-default btn-xs arrow-up", title: 'Up' do
                         = icon('arrow-up')
                       => link_to move_down_channel_message_path(@channel, message), method: :post, class: "btn btn-default btn-xs arrow-down", title: 'Down' do
                         = icon('arrow-down')
                   td.col-md-8
                     = link_to message.decorate.title_text, channel_message_path(@channel, message)
                     .small = message.type.gsub(/Message$/, "")
                     = message_subtext(@channel, message, index)
                   td.text-right.col-md-3
                     - if message.is_a?(ResponseMessage)
                       => link_to channel_message_response_actions_path(@channel, message), class: 'btn btn-default btn-xs', title: 'Response Actions' do
                         = icon('bolt')
                     - if @channel.broadcastable?
                       => link_to broadcast_channel_message_path(@channel, message), method: :post, class: "btn btn-default btn-xs", title: 'Broadcast' do
                         = icon('bullhorn')
                     => link_to "Edit", edit_channel_message_path(@channel, message), class: "btn btn-default btn-xs"
                     => link_to t(".destroy", default: t("helpers.links.destroy")),
                               channel_message_path(@channel,message),
                               method: :delete,
                               data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
                               class: "btn btn-xs btn-danger"
      .row
        .col-md-12.text-center
          = will_paginate @messages, param_name: "messages_page"

    - else
      .notification-well
        .icon
          span.glyphicon.glyphicon-envelope
        .message
          h4 No Messages
          p Add some messages to send to subscribers
          .add
            = link_to new_channel_message_path(@channel), class: "btn btn-primary"
              span.glyphicon.glyphicon-plus
              | Add new message

app/views/shared/_messages_list.html.slim
- message_model_class = Message

#messages-section.panel.panel-default
  .panel-heading
    .row
      .col-md-8
        .panel-title Messages
      .col-md-4.pull-right.text-right
        = link_to new_channel_message_path(@channel), class: "btn btn-primary btn-xs" do
          span.glyphicon.glyphicon-plus

  .panel-body
    - if @messages && @messages.size > 0
      .row
        .col-md-12
          - @message_counts_by_type.each do |type, count|
            => link_to "#{type.gsub(/Message$/, '')}(#{count})", channel_path(@channel, message_type: type)
          table.table.table-striped#messages_table
            thead
              tr
                th Text
                th
            tbody
              - messages.each_with_index do |message, index|
                tr id="message_#{message.id}"
                  td
                    = link_to message.title_text, channel_message_path(@channel, message)
                    .small = message.type.gsub(/Message$/, "")
                    = message_subtext(@channel, message, index)
                  td.text-right
                    - if @channel.broadcastable?
                        => link_to "Broadcast", broadcast_channel_message_path(@channel, message), method: :post, class: "btn btn-default btn-xs"
                    - if @channel.sequenced?
                        => link_to "Up", move_up_channel_message_path(@channel, message), method: :post, class: "btn btn-default btn-xs"
                        => link_to "Down", move_down_channel_message_path(@channel, message), method: :post, class: "btn btn-default btn-xs"
                    => link_to "Edit", edit_channel_message_path(@channel, message), class: "btn btn-default btn-xs"
                    => link_to t(".destroy", default: t("helpers.links.destroy")),
                              channel_message_path(@channel,message),
                              method: :delete,
                              data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
                              class: "btn btn-xs btn-danger"
      .row
        .col-md-12.text-center
          = will_paginate @messages, param_name: "messages_page"
    - else
      .notification-well
        .icon
          span.glyphicon.glyphicon-envelope
        .message
          h4 No Messages
          p Add some messages to send to subscribers
          .add
            = link_to "Add new message", new_channel_message_path(@channel), class: "btn btn-primary"

app/views/shared/_modal_window.html.slim
#modal-window.modal.hide.fade role='dialog aria-labelledby='myModalLabel' aria-hidden='true'

app/views/shared/_relative_schedule.html.slim
= f.input :relative_schedule_type,
          collection: %w(Minute Hour Day Week),
          include_blank: false,
          label: "Send at",
          input_html: { id: "relative-schedule-type" }

#relative-schedule-number
  = f.input :relative_schedule_number, label: "Number"

#relative-schedule-day
  = f.input :relative_schedule_day,
            collection: %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday),
            include_blank: false,
            label: "Day"

#relative-schedule-hour
  = f.input :relative_schedule_hour, label: "At Hr"

#relative-schedule-minute
  = f.input :relative_schedule_minute, label: "At Min"

- content_for :head_js
  javascript:
    function set_relative_schedule_controls(value) {
      $('#relative-schedule-number').css('display', 'inline');
      $('#relative-schedule-day').css('display', 'none');
      $('#relative-schedule-hour').css('display', 'none');
      $('#relative-schedule-minute').css('display', 'none');

      if (value === 'Minute') {
        // Not implemented yet.
      } else if (value === 'Hour') {
        $('#relative-schedule-minute').css('display', 'inline');
      } else if (value === 'Day') {
        $('#relative-schedule-hour').css('display', 'inline');
        $('#relative-schedule-minute').css('display', 'inline');
      } else if (value === 'Week') {
        $('#relative-schedule-day').css('display', 'inline');
        $('#relative-schedule-hour').css('display', 'inline');
        $('#relative-schedule-minute').css('display', 'inline');
      }
    }

    $(document).ready(function () {
      var $relativeScheduleType = $('#relative-schedule-type');
      
      set_relative_schedule_controls($relativeScheduleType.val());
      $relativeScheduleType.change(function () {
        set_relative_schedule_controls($(this).val());
      });
    });

app/views/shared/_rules_list.html.slim
- rule_model_class = Rule

#rules-section.panel.panel-default.shared-table
  .panel-heading
    .row
      .col-md-4
        | Rules
        span.badge.margin-left-10 #{@rules.count}
      .col-md-5
        = form_tag request.url, method: :get do
          .input-group
            = search_field_tag :rules_search, params[:rules_search], placeholder: 'Search by name or description', class: 'form-control'
            .input-group-btn
              = button_tag('Search', class: 'btn btn-default')
      .col-md-3.text-right.pull-right
        = link_to new_rule_path, class: "btn btn-primary btn-xs", id: 'rule-new'
          span.glyphicon.glyphicon-plus
          | New Rule
  .panel-body
    - if @rules && @rules.count > 0
      table.table.table-striped#rules_table
        thead
          th Name
          th.text-center Selection
          th.text-center If
          th.text-center Then
          th
        tbody
          - @rules.each do |rule|
            tr id="rule_#{rule.id}" class="rule-row-#{rule.active == true ? 'active' : 'not-active'}"
              td
                .name
                  = link_to rule.name, rule_path(rule)
                .description style="font-size: 80%; color: #ccc;"
                  = rule.description
              td.text-center = rule.selection
              td.text-center = rule.rule_if
              td.text-center = rule.rule_then
              td.text-right
                = link_to t(".edit", default: t("helpers.links.edit")),
                          edit_rule_path(rule),
                          class: "btn btn-default btn-xs"
      .row
        .col-md-12.text-center
          = will_paginate @rules, param_name: "rules_page"

    - else
      .notification-well.text-center
        .icon
          span.glyphicon.glyphicon-road
        .message
          h4 No Rules Defined
          p Rules let you perform arbitary actions, like changing a subscriber's channel, based on rules.
          .new
            = link_to new_rule_path, class: "btn btn-primary"
              span.glyphicon.glyphicon-plus
              | Add new rule

app/views/shared/_subscriber_list.html.slim
- subscriber_model_class = Subscriber

#subscribers-section.panel.panel-default.shared-table
  .panel-heading
    .row
      .col-md-4
        span.glyphicon.glyphicon-phone.margin-right-5
        | Subscribers
        span.badge.margin-left-10 #{@subscribers.count}
      .col-md-5
        = form_tag request.url, method: :get do
          .input-group
            = search_field_tag :subscribers_search, params[:subscribers_search], placeholder: 'Search by name or phone', class: 'form-control'
            .input-group-btn
              = button_tag('Search', class: 'btn btn-default')
      .col-md-3.text-right.pull-right
        = link_to new_subscriber_path, class: "btn btn-primary btn-xs", id: 'subscriber-new'
          span.glyphicon.glyphicon-plus
          | New Subscriber
  .panel-body
    - if @subscribers && @subscribers.count > 0
      table.table.table-striped#subscribers_table
        thead
          th = subscriber_model_class.human_attribute_name(:name)
          th.text-center =icon('phone')
          th.text-center =icon('list-ol')
          th
        tbody
          - @subscribers.each do |subscriber|
            tr id="subscriber_#{subscriber.id}"
              td = link_to subscriber.name, subscriber_path(subscriber)
              td.text-center = subscriber.phone_number
              td.text-center = subscriber.subscriptions.count
              td.text-right
                = link_to t(".edit", default: t("helpers.links.edit")),
                          edit_subscriber_path(subscriber),
                          class: "btn btn-default btn-xs"
      .row
        .col-md-12.text-center
          = will_paginate @subscribers, param_name: "subscribers_page"

    - else
      .notification-well.text-center
        .icon
          span.glyphicon.glyphicon-phone
        .message
          h4 No Subscribers
          p No subscribers have been added
          .new
            = link_to new_subscriber_path, class: "btn btn-primary" do
              span.glyphicon.glyphicon-plus
              | Add new subscriber