config/routes.rb
require 'sidekiq/web'

Liveinspired::Application.routes.draw do

  resources :chatrooms
  mount Sidekiq::Web => '/sidekiq'

  root :to => "home#index"
  devise_for :users
  namespace :admin do
    resources :home, only: %i(index)
    resources :channels, only: %i(index)
  end
  get 'admin', to: 'admin/home#index'
  resources :keywords, only: [:index]
  resources :chatrooms do
    resources :chatters, only: [:index] do
      collection do
        post :add_to_chatroom
        post :remove_from_chatroom
      end
    end
    resources :chats
  end
  resources :channels do
    member do
      get  'list_subscribers'
      get  'messages_report'
      post 'delete_all_messages'
      get  'timeline'
      get  'export'
      get  'all'
    end
    resources :messages do
      member do
        post 'broadcast'
        post 'move_up'
        post 'move_down'
        get  'responses'
      end
      collection do
        get 'select_import'
        post 'import'
        post 'update_seq_no'
      end
      resources :response_actions do
        collection do
          get 'select_import'
          post 'import'
        end
      end
    end
  end
  post 'channels/:channel_id/add_subscriber/:id',    to: 'channels#add_subscriber',    :as => 'channel_add_subscriber'
  post 'channels/:channel_id/remove_subscriber/:id', to: 'channels#remove_subscriber', :as => 'channel_remove_subscriber'

  resources :channel_groups, :except => [:index] do
    member do
      get 'messages_report'
    end
  end
  post 'channel_groups/:channel_group_id/remove_channel/:id', to: 'channel_groups#remove_channel',  :as => 'channel_group_remove_channel'

  resources :rules
  resources :users do
    member do
      get :activity
    end
  end
  resources :subscribers do
    resources :subscriber_responses, only: %i(index)
    member do
      get :download_activity
    end
  end
  resources :subscriber_activities, :except=>[:new,:create,:destroy] do
    member do
      post 'reprocess'
    end
  end

  resources :downloads,           only: [:index]
  resources :service_identifiers, only: [:index]

  match 'subscribe/:channel_group_id' => "home#new_web_subscriber", :via => [:get, :post]
  match 'thank_you' => "home#sign_up_success", via: [:get]
  match 'twilio' =>'twilio#callback', :via => [:post]

  match 'help/user_show',            via: [:get]
  match 'help/edit_channel',         via: [:get]
  match 'help/edit_message',         via: [:get]
  match 'help/index_channels',       via: [:get]
  match 'help/edit_response_action', via: [:get]
  match 'help/glossary',             via: [:get]

end

app/models/subscriber.rb
# == Schema Information
#
# Table name: subscribers
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  phone_number    :string(255)
#  remarks         :text
#  last_msg_seq_no :integer
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  email           :string(255)
#  deleted_at      :datetime
#

class Subscriber < ActiveRecord::Base
  include Mixins::ChatNames
  acts_as_paranoid
  attr_accessible :name, :phone_number, :remarks, :email, :additional_attributes

  belongs_to :user
  has_many   :rule_activities, as: :ruleable
  has_many   :subscriptions
  has_many   :channels, :through => :subscriptions
  has_many   :delivery_notices
  has_many   :delivery_error_notices
  has_many   :subscriber_responses
  has_many   :action_notices
  has_many   :chatroom_chatters, as: :chatter
  has_many   :chatrooms, through: :chatroom_chatters, source: :chatter, source_type: 'Subscriber'

  has_many   :chats, as: :chatter, dependent: :destroy

  scope :search, -> (search) { where('lower(name) LIKE ? OR phone_number LIKE ?',"%#{search.to_s.downcase}%","%#{search.to_s.downcase}%") }


  validates :phone_number, presence:true, phone_number:true,
    uniqueness:{scope:[:user_id,:deleted_at]}
  validates :email, format: {with:/\A.+@.+\z/}, allow_blank:true

  before_validation :normalize_phone_number

  def self.in_chatroom(chatroom)
    includes(:chatroom_chatters).where('chatroom_chatters.chatroom_id = ?', chatroom.id).references(:chatroom_chatters)
  end

  def self.find_by_phone_number(phone_number)
    ref_phone_number = Subscriber.format_phone_number(phone_number)
    where(phone_number:ref_phone_number).first
  end

  def self.custom_attributes_counts
    cac = {}
    find_each do |subx|
      subx.additional_attributes.to_s.split(';').each do |item|
        key, value = item.to_s.split("=", 2)
        cac[key] = 0 if cac[key].nil?
        cac[key] += 1
      end
    end
    cac
  end

  def custom_attributes
    @custom_attributes ||= begin
      sa = {}
      additional_attributes.to_s.split(";").each do |item|
        key, value = item.to_s.split("=", 2)
        key.downcase!
        sa[key] = value
        # try to convert it to a time or an integer
        time_value = Chronic.parse(value)
        int_value = value.to_i
        sa[key] = time_value if time_value
        sa[key] = int_value if sa[key].nil? && int_value != 0
      end
      sa
    end
  end

  def has_custom_attributes?
    if custom_attributes && custom_attributes.is_a?(Hash) && custom_attributes.keys.length > 0
      true
    else
      false
    end
  end

  def has_replied_to_message?(message)
    SubscriberResponse.where(subscriber_id: self.id, message_id: message.id).count > 0
  end

  def update_custom_attribute(key, val)
    custom_attributes[key.downcase] = val
    save_custom_attributes
  end

  def save_custom_attributes
    self.additional_attributes = ''
    custom_attributes.each_pair do |key, value|
      save_key = key.to_s.downcase
      self.additional_attributes << "#{save_key}=#{value.to_s};"
    end
    self.additional_attributes
    self.save if self.changed?
  end

  private

  def normalize_phone_number
    self.phone_number = Subscriber.format_phone_number(phone_number)
  end

  def self.format_phone_number(phone_number)
    return '' if phone_number.nil?
    return '' if phone_number.blank?
    digits = phone_number.gsub(/\D/,'').split(//)
    return nil if digits.length < 10 || digits.length > 11
    return "+1#{digits.join}" if digits.length == 10
    return "+#{digits.join}" if digits.length == 11
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  include Mixins::SubscriberSearch
  include Mixins::ChannelSearch
  include Mixins::ChannelGroupSearch
  include Mixins::AdministrativeLogging
  before_filter :load_subscriber
  skip_before_filter :load_subscriber, :only => [:new,:create,:index]
  before_filter :load_user, :only =>[:new, :create, :index, :show, :download_activity]

  def index
    session[:root_page] = subscribers_path
    #@subscribers = @user.subscribers.load
    handle_subscribers_query
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
    end
  end

  def show
    @timeline = Timeline.timeline(params.merge(:user_id => current_user.id))
    @sent_last_24_hours    = @subscriber.delivery_notices.where(created_at: 24.hours.ago..Time.now).count
    @replies_last_24_hours = @subscriber.subscriber_responses.where(created_at: 24.hours.ago..Time.now).count
    @errors_last_24_hours  = @subscriber.delivery_error_notices.where(created_at: 24.hours.ago..Time.now).count
    @actions_last_24_hours = @subscriber.action_notices.where(created_at: 24.hours.ago..Time.now).count

    helper = SubscriberAvailableChannels.new(params.merge(:user_id => current_user.id))
    @available_channels =  helper.channels.delete_if {|x| x.nil? }
    @subscribed_channel_ids = helper.subscribed_channel_ids

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  def download_activity
    log_user_activity("Downloaded subscriber activity for #{@subscriber.id}")
    @timeline = Timeline.timeline_export(params.merge(:user_id => current_user.id))
    download_data = CSV.generate({}) do |csv|
      csv << @timeline.first.keys
      @timeline.each do |row_array|
        csv << row_array.values
      end
    end
    respond_to do |format|
      format.csv { send_data download_data, filename: "subscriber-activity-#{@subscriber.id}-#{Date.today}.csv" }
      format.json { send_data @timeline.to_json, filename: "subscriber-activity-#{@subscriber.id}-#{Date.today}.json" }
    end
  end

  def new
    @subscriber = @user.subscribers.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscriber }
    end
  end

  def edit
  end

  def create
    @subscriber = @user.subscribers.new(params[:subscriber])

    respond_to do |format|
      if @subscriber.save
        log_user_activity("Created subscriber #{@subscriber.id}-#{@subscriber.name}", {subscriber_id: @subscriber.id })
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render json: @subscriber, status: :created, location: @subscriber }
      else
        format.html { render action: "new" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        log_user_activity("Changed subscriber #{@subscriber.id}-#{@subscriber.name}", {subscriber_id: @subscriber.id })
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @subscriber.destroy
    log_user_activity("Deleted subscriber #{@subscriber.id}-#{@subscriber.name}", {subscriber_id: @subscriber.id })

    respond_to do |format|
      format.html { redirect_to subscribers_path }
      format.json { head :no_content }
    end
  end

  private

  def load_user
    authenticate_user!
    @user = current_user
  end

  def load_subscriber
    authenticate_user!
    @user = current_user
    begin
      @subscriber = @user.subscribers.find(params[:id])
      redirect_to(root_url,alert:'Access Denied') unless @subscriber
    rescue
      redirect_to(root_url,alert:'Access Denied')
    end
  end
end

app/views/subscribers/_form.html.slim
= simple_form_for [@subscriber], wrapper: :horizontal_form, html: { class: "form-horizontal" } do |f|
  = f.input :name
  = f.input :phone_number
  = f.input :additional_attributes,
            input_html: { rows: 5 },
            hint: "These can replace placeholders in messages. e.g name=xxx;salutions=Mr;"
  = f.input :remarks, input_html: { rows: 5 }

  #page-actions
    .panel.panel-default
      .panel-body
        => f.button :submit, class: "btn-primary"
        => link_to "Cancel", session[:root_page] || request.referer, class: "btn btn-default"
        - unless @subscriber.new_record?
          => link_to t(".destroy", default: t("helpers.links.destroy")),
                    subscriber_path(@subscriber),
                    method: :delete,
                    data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
                    class: "btn btn-danger"

app/views/subscribers/edit.html.slim
- model_class = Subscriber

.page-header: h1
  = t ".title", default: [:"helpers.titles.edit", "Edit %{model}"], model: model_class.model_name.human.titleize

= render partial: "form"

app/views/subscribers/index.html.slim
- model_class = Subscriber

.page-header
  .row
    .col-md-8
      h4
        span.glyphicon.glyphicon-phone.margin-right-5
        | Subscribers
    .col-md-4.text-right.pull-right
      = link_to new_subscriber_path, class: "btn btn-primary btn-xs"
        span.glyphicon.glyphicon-plus
        | New Subscriber


.row
  .col-md-12
    = render partial: 'shared/subscriber_list'

app/views/subscribers/new.html.slim
- model_class = Subscriber

#page-header.page-header
  .row
    .col-md-8
      h4 New Subscriber
    .col-md-4.text-right.pull-right


.row
  .col-md-6
    = render partial: "form"
  .col-md-6
    h4.section-heading
      | Adding a new subscriber
    p
      | Adding a new subscriber is a straightforward process. Add a name (optional), a phone number, and any additional attributes.
    p
      | The additional attributes let you add an attribute that can be used in messages and rules-based processing.  To add an attribute, type attribute_name=attribute_value.
    p
      | Remarks are private. You can keep notes here.

app/views/subscribers/show.html.slim
- model_class = Subscriber

#page-header.page-header
  .row
    .col-md-4
      h4 Subscriber #{@subscriber.name}
      p = "#{@subscriber.phone_number}"
      - if !@subscriber.remarks.blank?
        p Remarks
        p = @subscriber.remarks
    .col-md-8
      .row
        .col-md-12
          h4.section-header.text-right
            | Last 24 Hours
          .row.text-right
            .col-md-2.pull-right
              .well.background-color-gallery.subscriber-info-widget
                .row
                  .col-md-4.text-left
                    .icon = icon('envelope', title: 'A message was sent to the subscriber', class: 'color-info fa-2x')
                  .col-md-8.text-right
                    .value = @sent_last_24_hours
                    .title.text-uppercase Sent
            .col-md-2.pull-right
              .well.background-color-gallery.subscriber-info-widget
                .row
                  .col-md-4.text-left
                    .icon = icon('reply', title: 'The subscriber replied.', class: 'color-success fa-2x')
                  .col-md-8.text-right
                    .value = @replies_last_24_hours
                    .title.text-uppercase Replies
            .col-md-2.pull-right
              .well.background-color-gallery.subscriber-info-widget
                .row
                  .col-md-4.text-left
                    .icon = icon('bolt', title: 'Action taken on subscriber account', class: 'color-info fa-2x')
                  .col-md-8.text-right
                    .value = @actions_last_24_hours
                    .title.text-uppercase Actions
            .col-md-2.pull-right
              .well.background-color-gallery.subscriber-info-widget
                .row
                  .col-md-4.text-left
                    .icon = icon('commenting', title: 'Chatrooms', class: 'color-info fa-2x')
                  .col-md-8.text-right
                    .value = @subscriber.chatrooms.count
                    .title.text-uppercase Chats
            .col-md-2.pull-right
              .well.background-color-gallery.subscriber-info-widget
                .row
                  .col-md-4.text-left
                    .icon = icon('exclamation', title: 'There was a problem', class: 'color-danger fa-2x')
                  .col-md-8.text-right
                    .value = @errors_last_24_hours
                    .title.text-uppercase Errors

.row
  .col-md-12
    .row
      .col-md-6
       .panel.with-nav-tabs.panel-default
         .panel-heading
           h4.section-header
             | Available Channels
             br
             span style="font-size: 85%;"
               = "Click "
               span.label.label-success
                 | Sub
               = " to add, or "
               span.label.label-danger
                 | Rem
               = " to remove channel)"
         .panel-body
           .row
             .col-md-12
               table.table.table-striped#subscribers-subscriptions-table
                 tbody
                   - Array(@available_channels).each do |channel|
                     - if @subscribed_channel_ids.include?(channel.id)
                       tr id="channel_#{channel.id}" data-subscribed="true"
                         td
                           span.label.label-success
                             | Sub
                         td = link_to "#{channel.id}-#{channel.name}", channel_path(channel.id)
                         td = link_to "Rem", channel_remove_subscriber_path(channel.id, @subscriber.id), method: :post, class: 'btn btn-danger btn-xs'
                     - else
                       tr id="channel_#{channel.id}" data-subscribed='false'
                         td
                           span
                         td = link_to "#{channel.id}-#{channel.name}", channel_path(channel.id)
                         td = link_to 'Add', channel_add_subscriber_path(channel.id, @subscriber.id), method: :post, class: 'btn btn-default btn-xs'
           .row
             .col-md-12.text-center
               = will_paginate @available_channels, param_name: "available_channels_page"

      .col-md-6.text-center
        .panel.with-nav-tabs.panel-default
          .panel-heading
            .row
              .col-md-4
                h4.section-header Messaging Activity
              .col-md-8
                ul.nav.nav-tabs.pull-right
                  li.active
                    a href="#combined" data-toggle='tab' Activity
                  li
                    a href="#send" data-toggle='tab' Send
                  li
                    a href="#receive" data-toggle='tab' Receive
          .panel-body
            .tab-content
              .tab-pane.fae.in.active#combined
                img src="http://#{ENV['STATSD_HOST']}/render/?width=500&height=400&_salt=1478272837.451&title=Subscriber%20Activity&lineMode=staircase&drawNullAsZero=true&areaMode=stacked&from=-7days&colorList=418acb%2Cred&hideLegend=false&uniqueLegend=true&fontName=Sans&target=alias(summarize(stats.counters.inspire.production.subscriber.#{@subscriber.id}.subscriber_response.count%2C%221h%22)%2C%22reply%22)&target=alias(summarize(stats.counters.inspire.production.subscriber.#{@subscriber.id}.message.*.delivery_notice.count%2C%221h%22)%2C%22message%20sent%22)"
              .tab-pane.fade.in#send
                img src="http://#{ENV['STATSD_HOST']}/render/?width=500&height=400&_salt=1478271805.688&title=Messages%20Sent&lineMode=staircase&drawNullAsZero=true&areaMode=stacked&from=-7days&colorList=418acb%2C418acb%2C418acb&target=summarize(stats.counters.inspire.production.subscriber.#{@subscriber.id}.message.*.delivery_notice.count%2C%221h%22)"
              .tab-pane.fade.in#receive
                img src="http://#{ENV['STATSD_HOST']}/render/?width=500&height=400&_salt=1478271999.161&title=Subscriber%20Responses&lineMode=staircase&drawNullAsZero=true&areaMode=stacked&from=-7days&colorList=418acb%2C418acb%2C418acb&target=summarize(stats.counters.inspire.production.subscriber.#{@subscriber.id}.subscriber_response.count%2C%221h%22)&hideLegend=true"

hr
.row
  .col-md-12
    h4.section-header.text-center
      | Recent Activity
    .row
      .col-md-12
        - if Array(@timeline).length > 0
          .row
            .col-md-12
              table#subscriber-timeline-list.table.table-striped
                thead
                  tr
                    th.text-center Type
                    th Activity
                    th.text-right
                      = icon('clock-o')
                tbody
                  - @timeline.each do |entry|
                    = render partial: "subscribers/timeline/#{entry.class.name.underscore}_row", locals: { entry: entry }
          .row
            .col-md-12.text-center
              = will_paginate @timeline, param_name: 'timeline_page'

        - else
          .notification-well
            .icon
              = icon('question')
            .title
              | No subscriber activity (yet)


#page-actions.row
  .col-md-12
    .panel.panel-default
      .panel-body
        => link_to "Back", request.referer, class: "btn btn-default"
        => link_to t(".edit", default: t("helpers.links.edit")),
                  edit_subscriber_path(@subscriber),
                  class: "btn btn-default"
        => link_to t(".destroy", default: t("helpers.links.destroy")),
                  subscriber_path(@subscriber),
                  method: :delete,
                  data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
                  class: "btn btn-danger"
        span.spacer
        div.btn-group
          a.btn.btn-default#show-subscriber-activities href="#{subscriber_activities_path(subscriber_id: @subscriber.id)}" Subscriber Activities
          button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
            span.caret
            span.sr-only Toggle Dropdown
          ul.dropdown-menu.pull-right role="menu"
            li
              a href="#{subscriber_activities_path(subscriber_id: @subscriber.id)}" View Subscriber Activities
            li.divider
            li
              a target="_blank" href="#{download_activity_subscriber_path(@subscriber.id)}.csv" Download CSV
            li
              a target="_blank" href="#{download_activity_subscriber_path(@subscriber.id)}.json" Download JSON